#!/bin/bash
# tag 2.6

tune_desktop=true

app_mode=
[ -n "$1" ] && app_mode=y

nimbix_desktop="/etc/JARVICE/nimbix_desktop"
sh -c "echo app_mode=$app_mode >>$nimbix_desktop"

xinitrc=/tmp/xinitrc
cat >$xinitrc <<EOF
#!/bin/bash -l

if [ -x /usr/bin/xscreensaver-command ]; then
  (sleep 5; /usr/bin/xscreensaver-command -exit) &
fi

xset s off -dpms >> /tmp/xfce4.log

echo "">>/tmp/xfce4.log
echo "=============================================" >>/tmp/xfce4.log
date >>/tmp/xfce4.log
echo "=============================================" >>/tmp/xfce4.log
EOF
chmod 755 $xinitrc
if [ -z "$app_mode" ]; then
    cat >>$xinitrc <<EOF
startxfce4 >>/tmp/xfce4.log 2>&1
EOF
else
    cat >>$xinitrc <<EOF
startxfce4 >>/tmp/xfce4.log 2>&1 &
exec $@
EOF
fi

if [[ "$tune_desktop" == "true" ]]; then # Should we live tune desktop?
  /usr/local/JARVICE/tools/setup/fine-tune.sh
fi # End desktop tuning

# tools=/usr/lib/JARVICE/tools

# Firefox Default Web Browser
cp /etc/skel/.config/xfce4/helpers.rc "$HOME/.config/xfce4/helpers.rc"
cp /etc/skel/.config/mimeapps.list "$HOME/.config/mimeapps.list"

# Add extra step to logout that stops the xvnc server
mkdir -p "$HOME/.config/autostart"
cp /tmp/.logout.desktop "$HOME/.config/autostart/logout.desktop"

while [ 1 ]; do
#    $tools/sbin/init $tools/bin/vncstart.sh $xinitrc
    /usr/local/JARVICE/tools/bin/vncstart.sh $xinitrc
    ret=$?
    if [ -n "$app_mode" ]; then
        rm -f $app_menu
        exit $ret
    else
        [ $ret -ne 0 ] && exit 0
    fi
    sleep 1
    vncserver -kill :1
    sleep 1
done
