#!/bin/bash
# tag 2.6

app_mode=
[ -n "$1" ] && app_mode=y

nimbix_desktop="/etc/JARVICE/nimbix_desktop"
sh -c "echo app_mode=$app_mode >>$nimbix_desktop"

xinitrc=/tmp/xinitrc
cat >$xinitrc <<EOF
#!/bin/bash -l

if [ -x /usr/bin/xscreensaver-command ]; then
  (sleep 5; /usr/bin/xscreensaver-command -exit) &
fi

xset s off -dpms >> /tmp/xfce4.log

echo "">>/tmp/xfce4.log
echo "=============================================" >>/tmp/xfce4.log
date >>/tmp/xfce4.log
echo "=============================================" >>/tmp/xfce4.log
EOF
chmod 755 $xinitrc
if [ -z "$app_mode" ]; then
    cat >>$xinitrc <<EOF
startxfce4 >>/tmp/xfce4.log 2>&1
EOF
else
    cat >>$xinitrc <<EOF
startxfce4 >>/tmp/xfce4.log 2>&1 &
exec $@
EOF
fi

xfrun_desktop="xfrun4.desktop"
[ ! -e /etc/redhat-release ] && xfrun_desktop="xfce4-run.desktop"
app_menu_dir=$HOME/.config/menus
app_menu=$app_menu_dir/xfce-applications.menu
mkdir -p $app_menu_dir

source /etc/os-release

if [[ "$ID_LIKE" == *"rhel"* ]]; then # EL based system
    if [[ "${VERSION_ID:0:1}" == "7" ]] || [[ "${VERSION_ID:0:1}" == "8" ]]; then
cat >$app_menu <<EOF
<!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"
  "http://www.freedesktop.org/standards/menu-spec/1.0/menu.dtd">

<Menu>
    <Name>Xfce</Name>

    <DefaultAppDirs/>
    <DefaultDirectoryDirs/>
    <DefaultMergeDirs/>

    <Include>
        <Category>X-Xfce-Toplevel</Category>
    </Include>

    <Layout>
        <Filename>$xfrun_desktop</Filename>
        <Separator/>
        <Filename>exo-terminal-emulator.desktop</Filename>
        <Filename>exo-file-manager.desktop</Filename>
    </Layout>

</Menu>
EOF
    fi
elif [[ "$ID" == *"ubuntu"* ]]; then # Ubuntu based system
    if [[ "$VERSION_ID" == "18.04" ]] || [[ "$VERSION_ID" == "20.04" ]]; then
cat >$app_menu <<EOF
<!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"
  "http://www.freedesktop.org/standards/menu-spec/1.0/menu.dtd">

<Menu>
    <Name>Xfce</Name>

    <DefaultAppDirs/>
    <DefaultDirectoryDirs/>
    <DefaultMergeDirs/>

    <Include>
        <Category>X-Xfce-Toplevel</Category>
    </Include>

    <Layout>
        <Filename>$xfrun_desktop</Filename>
        <Separator/>
        <Filename>exo-terminal-emulator.desktop</Filename>
        <Filename>exo-file-manager.desktop</Filename>
    </Layout>

</Menu>
EOF
    elif [[ "$VERSION_ID" == "22.04" ]]; then
cat >$app_menu <<EOF
<!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"
  "http://www.freedesktop.org/standards/menu-spec/1.0/menu.dtd">

<Menu>
    <Name>Xfce</Name>

    <DefaultAppDirs/>
    <DefaultDirectoryDirs/>
    <DefaultMergeDirs/>

    <Include>
        <Category>X-Xfce-Toplevel</Category>
    </Include>

    <Layout>
        <Filename>$xfrun_desktop</Filename>
        <Separator/>
        <Filename>xfce4-terminal-emulator.desktop</Filename>
        <Filename>xfce4-file-manager.desktop</Filename>
    </Layout>

</Menu>
EOF
    fi
fi

tools=/usr/lib/JARVICE/tools

while [ 1 ]; do
#    $tools/sbin/init $tools/bin/vncstart.sh $xinitrc
    /usr/local/JARVICE/tools/bin/vncstart.sh $xinitrc
    ret=$?
    if [ -n "$app_mode" ]; then
        rm -f $app_menu
        exit $ret
    else
        [ $ret -ne 0 ] && exit 0
    fi
    sleep 1
    vncserver -kill :1
    sleep 1
done

